### ISSUE TITLE
getRatePerSecond produces incorrect result on start of stream

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#66]
The token streaming game design is that a token will stream evenly (except for rounding) across some number of seconds (greater than zero).

However in `MasterOfCoinV1.getRatePerSecond`, during the first second, this produces the incorrect result. This cause incorrect results in `getGlobalRatePerSecond`.

Recommendation: update `stream.startTimestamp < block.timestamp` from exclusive less than to inclusive less than.

**Comment by ghoul-sol** [comment]
I don't think this is correct. When stream is created, `lastRewardTimestamp` is set as `_startTimestamp`. Then, pending rewards are calcualted by `getPendingRewards` which does 
```
    uint256 secondsFromLastPull = block.timestamp - lastRewardTimestamp;
    pendingRewards = secondsFromLastPull * stream.ratePerSecond;
```

When `stream.startTimestamp` is equal to `block.timestamp` no rewards will be paid because `secondsFromLastPull` will be `0`.

That's why the exclusive comparison is correct.

**Comment by fulldecent** [comment]
Thank you, that makes sense.

This means that if a stream is started at T and the stream lasts exactly one second (and blocks mine every second) then `getRatePerSecond` will always be zero (even during those two seconds).

I can't say the current behavior is wrong. But somebody might expect otherwise, and this function is part of the public interface, so it might be worth documenting this at the function level.
